apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-app-deployment
  labels:
    app: flyway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyway
  template:
    metadata:
      labels:
        app: flyway
        type: backend
    spec:
      containers:
      - name: app-service
        image: skedia/app-service:dev
        env:
        - name: env
          value: dev
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: flyway-app-nodeport-service
  labels:
    app: flyway
spec:
  type: NodePort
  selector:
    app: flyway
    type: backend
  ports:
    - port: 8081 # service port which diverts traffic to your application
      targetPort: 8080 # port of application running in container
      nodePort: 30080 # port on which the application can be accessed
  clusterIP: 10.96.0.2 # cluster ip can be used by applications internally to communicate between them