# Oracle JRE8
FROM store/oracle/serverjre:8
#Build time arguments
ENV env dev
#Echo env variable
RUN echo $env
# copy JAR into image
COPY ./target/app-service-0.0.1-SNAPSHOT.jar /hackathon/app-service-0.0.1-SNAPSHOT.jar
# run application with this command line 
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=$env", "/hackathon/app-service-0.0.1-SNAPSHOT.jar"]