spring:
  profiles:
    active: dev
    hibernate:
      ddl-auto: validate
      
server:
  servlet:
    contextPath: /flyway

---

spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
          
---

spring:
  profiles: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: admin
      
---

spring:
  profiles: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/proddb?useSSL=false
    username: root
    password: admin