spring:
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      
server:
  servlet:
    contextPath: /flyway

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/devdb?useSSL=false
    username: root
    password: admin
          
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: admin
      
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/proddb?useSSL=false
    username: root
    password: admin