apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-app-frontend
  labels:
    app: flyway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyway
  template:
    metadata:
      labels:
        app: flyway
        type: frontend
    spec:
      containers:
      - name: app-ui
        image: skedia/app-ui:1.0.1
        ports:
        - containerPort: 80