apiVersion: v1
kind: Service
metadata:
  name: flyway-app-frontend-service
  labels:
    app: flyway
spec:
  type: NodePort
  selector:
    app: flyway
    type: frontend
  ports:
    - port: 80 # service port which diverts traffic to your application
      targetPort: 80 # port of application running in container
      nodePort: 30081 # port on which the application can be accessed
  clusterIP: 10.96.0.3 # cluster ip can be used by applications internally to communicate between them